external/chre: Fix missing-field-initializers errors
Log:
  /PATH/TO/chre/apps/external/android/system/chre/chre/platform/nuttx/test.cc:145:
  /PATH/TO/chre/test/nuttx/settings_test.cc: In function 'bool chre::{anonymous}::start()':
  /PATH/TO/chre/test/nuttx/settings_test.cc:51:3: error: missing initializer for member 'chreWifiNanSubscribeConfi
  g::serviceSpecificInfo' [-Werror=missing-field-initializers]
     51 |   };
        |   ^
  /PATH/TO/chre/test/nuttx/settings_test.cc:51:3: error: missing initializer for member 'chreWifiNanSubscribeConfi
  g::serviceSpecificInfoSize' [-Werror=missing-field-initializers]
  /PATH/TO/chre/test/nuttx/settings_test.cc:51:3: error: missing initializer for member 'chreWifiNanSubscribeConfi
  g::matchFilter' [-Werror=missing-field-initializers]
  /PATH/TO/chre/test/nuttx/settings_test.cc:51:3: error: missing initializer for member 'chreWifiNanSubscribeConfi
  g::matchFilterLength' [-Werror=missing-field-initializers]

Signed-off-by: wangjianyu3 <wangjianyu3@xiaomi.com>