external/chre: Fix maybe-uninitialized errors
Log:
  In file included from /PATH/TO/chre/platform/nuttx/test.cc:144:
  In function 'bool chre::{anonymous}::waitForCondition(const std::__1::function<bool()>&, std::__1::chrono::milliseconds)',
      inlined from 'virtual void chre::{anonymous}::TestBase_GnssSubscriptionWithSettingChange_Test::TestBody()' at /home/dramalife/sdb/dev.vela.qemu-arm64-v8a-ap/apps/external/android/s
  ystem/chre/chre/test/nuttx/gnss_test.cc:145:3:
  /PATH/TO/chre/test/nuttx/gnss_test.cc:48:34: error: 'time.std::__1::chrono::duration<long long int, std::__1::ra
  tio<1, 1000> >::__rep_' may be used uninitialized [-Werror=maybe-uninitialized]
     48 |   while (!(result = predicate()) && time < timeout) {
        |          ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
  /PATH/TO/chre/test/nuttx/gnss_test.cc: In member function 'virtual void chre::{anonymous}::TestBase_GnssSubscrip
  tionWithSettingChange_Test::TestBody()':
  /PATH/TO/chre/test/nuttx/gnss_test.cc:47:29: note: 'time.std::__1::chrono::duration<long long int, std::__1::rat
  io<1, 1000> >::__rep_' was declared here
     47 |   std::chrono::milliseconds time;
        |                             ^~~~

Signed-off-by: wangjianyu3 <wangjianyu3@xiaomi.com>